config/routes.rb
Rails.application.routes.draw do
  
  

  resources :seats
  resources :trainfares
  resources :stations
  resources :trainclasses
  resources :trainroutes
  resources :reservations
  resources :trains 
  root 'login#index'
  get 'welcome/index'
  get'welcome/contact'
   devise_for :users , controllers: { registrations: "registrations"}

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  resources :statuses
  get "/geocoding", to: "pages#geocoding", as: "geocoding"
  
   

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

     user ||= User.new
   if user.has_role? :admin
     can :manage, :all
   elsif user.has_role? :passenger
     can :create, Status  #author can create status
     can :update, Status # author can update status
     can :destroy,Status 
     # can :destroy, Status # #uncomment this line, author can destroy status 
     
     can :read , Trainroute
     can :create, Reservation# author can create status
    can :destroy, Reservation
    can :update ,  Reservation
    can :read, Reservation
    can :read ,Trainfare
     # can :destroy, Status # #uncomment this line, author can destroy status 
       else
     can :read, :all
   end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
belongs_to :trainroute
belongs_to :user
validates_numericality_of :seats, only_integer: true, greater_than: 0 


	after_save :decrement_totalseat

def decrement_totalseat
		c= self.trainroute
		c.update(totalseat: c.totalseat-1)
		
	end

end

app/models/seat.rb
class Seat < ActiveRecord::Base
end

app/models/station.rb
class Station < ActiveRecord::Base

	belongs_to :trainroute


validates_length_of :name, maximum: 20
validates_presence_of :name
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/train.rb
class Train < ActiveRecord::Base
	has_many :trainroutes, dependent: :destroy
	has_many :trainfares , dependent: :destroy
	# has_many :trainclasses, dependent: :destroy

	
validates_presence_of :name,:traintype
	
end

app/models/trainclass.rb
class Trainclass < ActiveRecord::Base
	belongs_to :train
	has_many :reservations, dependent: :destroy
	has_many :trainroutes, through: :reservations

	validates_inclusion_of :name, in: %w( Business Sleeper Economy)
	validates_numericality_of :fare, only_integer: true, greater_than: 0 
	validates_numericality_of :totalseats, only_integer: true, greater_than: 0
	validates_presence_of :name, :train_id, :totalseats, :fare
end

app/models/trainfare.rb
class Trainfare < ActiveRecord::Base
	belongs_to :train

	
end

app/models/trainroute.rb
class Trainroute < ActiveRecord::Base
	belongs_to :train
	has_many :reservations ,dependent: :destroy
	has_many :users, through: :reservations

	validates_presence_of :deptdate,:arrivaldate ,:deptime, :train_id, :arrivaltime
	


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations
  has_many :trainroutes, through: :reservations
  validates :email, presence: true , uniqueness: true , format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 cattr_accessor :current_user

 ROLES = %i[admin passenger]

 def roles=(roles)
   roles = [*roles].map { |r| r.to_sym }
   self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
 end

 def roles
   ROLES.reject do |r|
     ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
   end
 end

 def has_role?(role)
   roles.include?(role)
 end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
 before_action :authenticate_user!


   load_and_authorize_resource
   layout :choose_layout
  before_action :set_station, only: [:show, :edit, :update, :destroy]


  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name)
    end

    def choose_layout
      puts "#"*100, user_signed_in?, current_user.admin?
      if user_signed_in? and current_user.admin?
        "admin_layout"
      else
        "passenger_layout"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/trainclasses_helper.rb
module TrainclassesHelper
end

app/helpers/trainfares_helper.rb
module TrainfaresHelper
end

app/helpers/trainroutes_helper.rb
module TrainroutesHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field-area" style="padding:20px;">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div >
    <%= f.submit "Save" , class:"form_btn" ,style:"margin:20px;" %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1 class="w3-center">Editing Station</h1>
<div class="form">
<%= render 'form' %>

<%= link_to 'Back', stations_path , class:"admin_btn"%>
</div>

app/views/stations/index.html.erb
<%= link_to 'New Station', new_station_path , class:"add_btn", style:"margin-left:40px; margin-top:5px;"%>
<h1 class="w3-center"> Stations</h1>
<div class="tablecenter">
<table id="customers" >
  <thead>
    <tr>
      <th>Station ID</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.id%></td>
        <td><%= station.name %></td>
        <td><%= link_to 'Edit', edit_station_path(station), class:"contact_btn" %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } ,class:"contact_btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<br>

app/views/stations/new.html.erb
<h1 class="w3-center">New Station</h1>
<div class="form">
<%= render 'form' %>

<%= link_to 'Back', stations_path ,class:"admin_btn"%>
</div>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>