config/routes.rb
Rails.application.routes.draw do
  
  

  resources :seats
  resources :trainfares
  resources :stations
  resources :trainclasses
  resources :trainroutes
  resources :reservations
  resources :trains 
  root 'login#index'
  get 'welcome/index'
  get'welcome/contact'
   devise_for :users , controllers: { registrations: "registrations"}

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  resources :statuses
  get "/geocoding", to: "pages#geocoding", as: "geocoding"
  
   

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

     user ||= User.new
   if user.has_role? :admin
     can :manage, :all
   elsif user.has_role? :passenger
     can :create, Status  #author can create status
     can :update, Status # author can update status
     can :destroy,Status 
     # can :destroy, Status # #uncomment this line, author can destroy status 
     
     can :read , Trainroute
     can :create, Reservation# author can create status
    can :destroy, Reservation
    can :update ,  Reservation
    can :read, Reservation
    can :read ,Trainfare
     # can :destroy, Status # #uncomment this line, author can destroy status 
       else
     can :read, :all
   end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
belongs_to :trainroute
belongs_to :user
validates_numericality_of :seats, only_integer: true, greater_than: 0 


	after_save :decrement_totalseat

def decrement_totalseat
		c= self.trainroute
		c.update(totalseat: c.totalseat-1)
		
	end

end

app/models/seat.rb
class Seat < ActiveRecord::Base
end

app/models/station.rb
class Station < ActiveRecord::Base

	belongs_to :trainroute


validates_length_of :name, maximum: 20
validates_presence_of :name
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/train.rb
class Train < ActiveRecord::Base
	has_many :trainroutes, dependent: :destroy
	has_many :trainfares , dependent: :destroy
	# has_many :trainclasses, dependent: :destroy

	
validates_presence_of :name,:traintype
	
end

app/models/trainclass.rb
class Trainclass < ActiveRecord::Base
	belongs_to :train
	has_many :reservations, dependent: :destroy
	has_many :trainroutes, through: :reservations

	validates_inclusion_of :name, in: %w( Business Sleeper Economy)
	validates_numericality_of :fare, only_integer: true, greater_than: 0 
	validates_numericality_of :totalseats, only_integer: true, greater_than: 0
	validates_presence_of :name, :train_id, :totalseats, :fare
end

app/models/trainfare.rb
class Trainfare < ActiveRecord::Base
	belongs_to :train

	
end

app/models/trainroute.rb
class Trainroute < ActiveRecord::Base
	belongs_to :train
	has_many :reservations ,dependent: :destroy
	has_many :users, through: :reservations

	validates_presence_of :deptdate,:arrivaldate ,:deptime, :train_id, :arrivaltime
	


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations
  has_many :trainroutes, through: :reservations
  validates :email, presence: true , uniqueness: true , format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 cattr_accessor :current_user

 ROLES = %i[admin passenger]

 def roles=(roles)
   roles = [*roles].map { |r| r.to_sym }
   self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
 end

 def roles
   ROLES.reject do |r|
     ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
   end
 end

 def has_role?(role)
   roles.include?(role)
 end
end

app/controllers/trainroutes_controller.rb
class TrainroutesController < ApplicationController
  
  before_action :authenticate_user!


  load_and_authorize_resource
  layout :choose_layout

  before_action :set_trainroute, only: [:show, :edit, :update, :destroy]
  

  # GET /trainroutes
  # GET /trainroutes.json
  def index
    @q = Trainroute.where(available: true).ransack(params[:q])
    
    distances = [];
    if @q.result(distinct: true).length > 0
      @trainroutes = @q.result(distinct: true)
    else
      @searched_destination = Trainroute.where(source: params[:q][:source_cont], destination: params[:q][:destination_cont])
      @same_destinations = Trainroute.where(destination: params[:q][:destination_cont])
      (@same_destinations - @searched_destination).each do |sd|
        distances.push((@searched_destination.first.distance - sd.distance).abs)
      end
      selected_id  = @same_destinations.select{|d| (@searched_destination.first.distance - d.distance).abs == distances.min}.first.id 
      @trainroutes = Trainroute.where(id: selected_id)
    end
    @trainroutes
  end

  # GET /trainroutes/1
  # GET /trainroutes/1.json
  def show
  end

  # GET /trainroutes/new
  def new
    @trainroute = current_user.trainroutes.build  
  end

  # GET /trainroutes/1/edit
  def edit
  end

  # POST /trainroutes
  # POST /trainroutes.json
  def create
    @trainroute = current_user.trainroutes.build(trainroute_params)

    respond_to do |format|
      if @trainroute.save
        format.html { redirect_to @trainroute, notice: 'Trainroute was successfully created.' }
        format.json { render :show, status: :created, location: @trainroute }
      else
        format.html { render :new }
        format.json { render json: @trainroute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainroutes/1
  # PATCH/PUT /trainroutes/1.json
  def update
    respond_to do |format|
      if @trainroute.update(trainroute_params)
        format.html { redirect_to @trainroute, notice: 'Trainroute was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainroute }
      else
        format.html { render :edit }
        format.json { render json: @trainroute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainroutes/1
  # DELETE /trainroutes/1.json
  def destroy
    @trainroute.destroy
    respond_to do |format|
      format.html { redirect_to trainroutes_url, notice: 'Trainroute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainroute
      @trainroute = Trainroute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainroute_params
      params.require(:trainroute).permit(:train_id, :source, :destination, :deptdate, :arrivaldate, :deptime, :arrivaltime, :name, :distance, :totalseat)
    end

    def choose_layout
      puts "#"*100, user_signed_in?, current_user.admin?
      if user_signed_in? and current_user.admin?
        "admin_layout"
      else
        "passenger_layout"
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/trainclasses_helper.rb
module TrainclassesHelper
end

app/helpers/trainfares_helper.rb
module TrainfaresHelper
end

app/helpers/trainroutes_helper.rb
module TrainroutesHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/trainroutes/_form.html.erb
<%= form_for(@trainroute) do |f| %>
  <% if @trainroute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trainroute.errors.count, "error") %> prohibited this trainroute from being saved:</h2>

      <ul>
      <% @trainroute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field-area">
    <%= f.label :train_id %><br>
    <%= f.number_field :train_id %>
  </div>
    <div class="field-area">
    <%= f.label :name,'Train Name' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field-area">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field-area">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field-area">
    <%= f.label :distance %><br>
    <%= f.number_field :distance %>
  </div>
  <div class="field-area">
    <%= f.label :deptdate %><br>
    <%= f.date_select :deptdate %>
  </div>
  <div class="field-area">
    <%= f.label :arrivaldate %><br>
    <%= f.date_select :arrivaldate %>
  </div>
  <div class="field-area">
    <%= f.label :deptime %><br>
    <%= f.time_select :deptime %>
  </div>
  <div class="field-area">
    <%= f.label :arrivaltime %><br>
    <%= f.time_select :arrivaltime %>
  </div>
  <div class="field-area">
    <%= f.label :totalseat,'Available Seat' %><br>
    <%= f.number_field :totalseat %>
  </div>
  <div class="field-area">
    <%= f.label :available,'Available' %><br>
    <%= f.check_box :available %>
  </div>
  <div class="form_btn">
    <%= f.submit "Save"%>
  </div>
<% end %>

app/views/trainroutes/edit.html.erb
<h1  class="w3-center">Editing Trainroute</h1>
<div class="form">
<%= render 'form' %>

<%= link_to 'Back', trainroutes_path , class:"admin_btn"%>
</div>

app/views/trainroutes/index.html.erb
<% if can? :create  , @trainroute %>
<%= link_to 'Add Route', new_trainroute_path , class:"add_btn" , style:"margin-left:40px; margin-top:5px;"%>
<% end %>
<br>
<h1 class="w3-center">Trains Schedule</h1>

<div class="tablecenter">
<%= search_form_for @q do |f| %>

<div class="field-wrap1">
<%= f.label :source %>
  <%= f.search_field :source_cont %>
</div>
  

<div  class="field-wrap2">
<%= f.label :destination %>
  <%= f.search_field :destination_cont%>
</div>
  
  <%= f.submit "Search" ,class:"search_btn" %>
<% end %>

<br>
<table id="customers">
  <thead>
    <tr>
      <th>Route ID</th>
      <th>Train Name</th>
      <th>Source</th>
      <th>Destination</th>
      <th>Distance</th>
      <th>Deptdate</th>
      <th>Arrivaldate</th>
      <th>Deptime</th>
      <th>Arrivaltime</th>
      <th>Available seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainroutes.each do |trainroute| %>
      <tr>
        <td><%= trainroute.id %></td>
        <td><%= trainroute.name %></td>
        <td><%= trainroute.source %></td>
        <td><%= trainroute.destination %></td>
        <td><%= trainroute.distance %></td>
        <td><%= trainroute.deptdate %></td>
        <td><%= trainroute.arrivaldate %></td>
        <td><%= trainroute.deptime %></td>
        <td><%= trainroute.arrivaltime %></td>
      <td><%= trainroute.totalseat%></td>


        <% if can? :update , @trainroute %>
        <td><%= link_to 'Edit', edit_trainroute_path(trainroute),class:"admin_btn" %></td>
        <%end%>

         <% if can? :destroy , @trainroute %>
         <td><%= link_to 'Destroy', trainroute, class:"admin_btn",method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>


        <td><%= link_to 'Book' ,new_reservation_path(trainroute) , class:"admin_btn" %></td>

       
        
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/trainroutes/new.html.erb
<h1 class="w3-center">New Trainroute</h1>
<div class="form ">

<%= render 'form' %>

<%= link_to 'Back', trainroutes_path %>
</div>

app/views/trainroutes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Train:</strong>
  <%= @trainroute.train_id %>
</p>

<p>
  <strong>Source:</strong>
  <%= @trainroute.source %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @trainroute.destination %>
</p>

<p>
  <strong>Deptdate:</strong>
  <%= @trainroute.deptdate %>
</p>

<p>
  <strong>Arrivaldate:</strong>
  <%= @trainroute.arrivaldate %>
</p>

<p>
  <strong>Deptime:</strong>
  <%= @trainroute.deptime %>
</p>

<p>
  <strong>Arrivaltime:</strong>
  <%= @trainroute.arrivaltime %>
</p>

<%= link_to 'Edit', edit_trainroute_path(@trainroute) %> |
<%= link_to 'Back', trainroutes_path %>